### ISSUE TITLE
Global plot with sinusoidal projection

### ISSUE THREAD

**Issue by judithhubbard** [kyleedwardbradley/tectoplot#12]
Probably is not supposed to produce this.

tectoplot -RJ S 130 -r g -zcat ANSS -zmag 4 10 -z -znoplot -seissum 0.5 -o sinusoidal

Also, when I run -seissum, the system spits out the resolution during processing (but no other processing info)

 
![image](https://user-images.githubusercontent.com/84396466/124369208-d9f9cb00-dc9b-11eb-88d2-b052bc38a65d.png)

**Comment by kyleedwardbradley** [comment]
Fixed for now by suppressing recalculation of region for -RJ S, F, and G.
