### ISSUE TITLE
Criss-crossing cross sections may not properly plot all seismicity

### ISSUE THREAD

**Issue by judithhubbard** [kyleedwardbradley/tectoplot#17]
...as planned for parallel cross sections. But unexpected problems for Hawaii.

**Comment by kyleedwardbradley** [comment]
Default behavior was to plot data only on closest profile, which causes problems with profiles that cross. This behavior is now off by default and can be turned on using -setvars { PROFILE_USE_CLOSEST 1 }. It is recommended for parallel profiles with overlap if you don't want events duplicated on different profiles.
