### ISSUE TITLE
Gorkha eq incorrectly labelled as mag 7.0. 

### ISSUE THREAD

**Issue by judithhubbard** [kyleedwardbradley/tectoplot#3]
[nepal.pdf](https://github.com/kyleedwardbradley/tectoplot/files/6519961/nepal.pdf)

tectoplot -r NP -t -t0 -zcat ISC -z -o nepal -eqlabel 7

ISC listing here: http://www.isc.ac.uk/cgi-bin/web-db-v4?request=COMPREHENSIVE&out_format=CATCSV&searchshape=RECT&bot_lat=27&top_lat=29&left_lon=83&right_lon=86&ctr_lat=&ctr_lon=&radius=&max_dist_units=deg&srn=&grn=&start_year=2015&start_month=1&start_day=28&start_time=00%3A00%3A00&end_year=2016&end_month=3&end_day=01&end_time=00%3A00%3A00&min_dep=&max_dep=&min_mag=7&max_mag=&req_mag_type=&req_mag_agcy=&include_links=on

**Comment by kyleedwardbradley** [comment]
I updated the code to select the largest magnitude from the list of alternatives, and report the alternative selections in the /seismicity/mag_selections.dat file.
