### ISSUE TITLE
Gray edges when plotting with UTM projection.

### ISSUE THREAD

**Issue by judithhubbard** [kyleedwardbradley/tectoplot#7]
tectoplot -r 68 105 25 46 -t 01m -t0 -RJ UTM

![image](https://user-images.githubusercontent.com/84396466/119956248-795bdc00-bfd3-11eb-975c-0966a5c0d3b0.png)

**Comment by kyleedwardbradley** [comment]
This is fixed by not setting the recalcregionflag_lonlat to 1 in the -RJ UTM section. Not sure if it will break something else.
